### ISSUE TITLE
VHDL plugin doesn't work with latest Yosys (0.7+591)

### ISSUE THREAD

**Issue by rick-heig** [cliffordwolf/yosys-plugins#2]
Hello.
Compiling this plugin with
`$ make`
results in the following error : 
```
vhdl_frontend.cc:326:250: error: too few arguments to function call, expected 17, have 16
  ...AST::process(design, current_ast, flag_dump_ast1, flag_dump_ast2, flag_dump_vlog, flag_dump_rtlil,
 flag_nolatches, flag_nomeminit, flag_nomem2reg, flag_mem2reg, flag_lib, flag_noopt, flag_icells, flag_
ignore_redef, flag_defer, default_nettype_wire);                                                      
     ~~~~~~~~~~~~                                                                                      
                                                                                                       
                                              ^                                                       
/usr/local/share/yosys/include/frontends/ast/ast.h:277:2: note: 'process' declared here
        void process(RTLIL::Design *design, AstNode *ast, bool dump_ast1, bool dump_ast2, bool ...
        ^
1 error generated.
```

I was able to fix it with the following change : 

```
diff --git a/vhdl/vhdl_frontend.cc b/vhdl/vhdl_frontend.cc
index 3f7d276..a2db5b4 100644
--- a/vhdl/vhdl_frontend.cc
+++ b/vhdl/vhdl_frontend.cc
@@ -170,6 +170,7 @@ struct VHDLFrontend : public Frontend {
 		bool flag_ignore_redef = false;
 		bool flag_defer = false;
 		bool flag_dump_rtlil = false;
+                bool flag_redef = false;
 		std::map<std::string, std::string> defines_map;
 		std::list<std::string> include_dirs;
 		std::list<std::string> attributes;
@@ -323,7 +324,7 @@ struct VHDLFrontend : public Frontend {
 		if (flag_nodpi)
 			error_on_dpi_function(current_ast);
 
-		AST::process(design, current_ast, flag_dump_ast1, flag_dump_ast2, flag_dump_vlog, flag_dump_rtlil, flag_nolatches, flag_nomeminit, flag_nomem2reg, flag_mem2reg, flag_lib, flag_noopt, flag_icells, flag_ignore_redef, flag_defer, default_nettype_wire);
+		AST::process(design, current_ast, flag_dump_ast1, flag_dump_ast2, flag_dump_vlog, flag_dump_rtlil, flag_nolatches, flag_nomeminit, flag_nomem2reg, flag_mem2reg, flag_lib, flag_noopt, flag_icells, flag_ignore_redef, flag_redef, flag_defer, default_nettype_wire);
 
 		if (!flag_nopp)
 			delete lexin;
```

**Comment by cliffordwolf** [comment]
Thanks! Fixed in dd60cf4.
